### ISSUE TITLE
Mobile Screen Archetypes image links broken

### ISSUE THREAD

**Issue by IAmUli** [codepath/android_guides#252] opened 2017-01-27 18:45 UTC
All the image links on this page are dead. https://github.com/codepath/android_guides/wiki/Mobile-Screen-Archetypes

**Comment by nesquena** [comment] 2017-01-27 18:47
Thanks for reporting this, the site we were linking to for those images went offline. Closing as a duplicate of https://github.com/codepath/android_guides/issues/247

**Closed by nesquena** 2017-01-27 18:47 UTC
